# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\GOT24\Desktop\python_project\Nut\Advice.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Advice(object):
    def setupUi(self, Advice):
        Advice.setObjectName("Advice")
        Advice.resize(800, 600)
        Advice.setMinimumSize(QtCore.QSize(600, 400))
        Advice.setMaximumSize(QtCore.QSize(800, 600))
        self.centralwidget = QtWidgets.QWidget(Advice)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(150, 120, 508, 451))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Bt_Obese = QtWidgets.QPushButton(self.layoutWidget)
        self.Bt_Obese.setMinimumSize(QtCore.QSize(0, 51))
        self.Bt_Obese.setStyleSheet("font: 15pt \"MV Boli\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 0, 0);")
        self.Bt_Obese.setObjectName("Bt_Obese")
        self.verticalLayout.addWidget(self.Bt_Obese)
        self.Bt_Overweight = QtWidgets.QPushButton(self.layoutWidget)
        self.Bt_Overweight.setStyleSheet("font: 15pt \"MV Boli\";\n"
"background-color: rgb(255, 237, 34);\n"
"color: rgb(0, 0, 0);")
        self.Bt_Overweight.setObjectName("Bt_Overweight")
        self.verticalLayout.addWidget(self.Bt_Overweight)
        self.Bt_Normal = QtWidgets.QPushButton(self.layoutWidget)
        self.Bt_Normal.setStyleSheet("font: 15pt \"MV Boli\";\n"
"background-color: rgb(170, 255, 0);")
        self.Bt_Normal.setObjectName("Bt_Normal")
        self.verticalLayout.addWidget(self.Bt_Normal)
        self.Bt_Underweight = QtWidgets.QPushButton(self.layoutWidget)
        self.Bt_Underweight.setStyleSheet("font: 15pt \"MV Boli\";")
        self.Bt_Underweight.setObjectName("Bt_Underweight")
        self.verticalLayout.addWidget(self.Bt_Underweight)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 0, 781, 51))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.textBrowser = QtWidgets.QTextBrowser(self.layoutWidget1)
        self.textBrowser.setMinimumSize(QtCore.QSize(361, 41))
        self.textBrowser.setObjectName("textBrowser")
        self.horizontalLayout.addWidget(self.textBrowser)
        self.HomeButton = QtWidgets.QPushButton(self.centralwidget)
        self.HomeButton.setGeometry(QtCore.QRect(10, 470, 131, 51))
        self.HomeButton.setStyleSheet("font: 75 24pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(85, 170, 127);")
        self.HomeButton.setObjectName("HomeButton")
        self.label_YourBMI = QtWidgets.QLabel(self.centralwidget)
        self.label_YourBMI.setGeometry(QtCore.QRect(190, 80, 291, 61))
        self.label_YourBMI.setStyleSheet("color: rgb(255, 0, 0);\n"
"font: 63 36pt \"Yu Gothic UI Semibold\";")
        self.label_YourBMI.setObjectName("label_YourBMI")
        self.label_ShowBMI = QtWidgets.QLabel(self.centralwidget)
        self.label_ShowBMI.setGeometry(QtCore.QRect(490, 80, 151, 61))
        self.label_ShowBMI.setStyleSheet("font: 63 36pt \"Yu Gothic UI Semibold\";\n"
"color: rgb(0, 170, 255);")
        self.label_ShowBMI.setObjectName("label_ShowBMI")
        Advice.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Advice)
        self.statusbar.setObjectName("statusbar")
        Advice.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(Advice)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menuBar.setObjectName("menuBar")
        Advice.setMenuBar(self.menuBar)

        self.retranslateUi(Advice)
        QtCore.QMetaObject.connectSlotsByName(Advice)

    def retranslateUi(self, Advice):
        _translate = QtCore.QCoreApplication.translate
        Advice.setWindowTitle(_translate("Advice", "Advice"))
        self.Bt_Obese.setText(_translate("Advice", "อ้วน( Obese ) | BMI  >25"))
        self.Bt_Overweight.setText(_translate("Advice", "น้ำหนักเกิน(Overweight ) | BMI : 23-24.9"))
        self.Bt_Normal.setText(_translate("Advice", "น้ำหนักปกติ(Normal) | BMI : 18.5-22.9"))
        self.Bt_Underweight.setText(_translate("Advice", "น้ำหนักน้อย(Underweight) | BMI : <18.5"))
        self.textBrowser.setHtml(_translate("Advice", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600;\">รายการคำแนะนำ</span></p></body></html>"))
        self.HomeButton.setToolTip(_translate("Advice", "<html><head/><body><p><span style=\" font-size:12pt;\">home</span></p></body></html>"))
        self.HomeButton.setText(_translate("Advice", "Home"))
        self.label_YourBMI.setToolTip(_translate("Advice", "<html><head/><body><p>YourBMI</p></body></html>"))
        self.label_YourBMI.setText(_translate("Advice", "Your BMI :"))
        self.label_ShowBMI.setText(_translate("Advice", ":"))
