# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\GOT24\Desktop\python_project\Nut\Obese.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Obese(object):
    def setupUi(self, Obese):
        Obese.setObjectName("Obese")
        Obese.resize(800, 600)
        Obese.setMinimumSize(QtCore.QSize(600, 400))
        Obese.setMaximumSize(QtCore.QSize(800, 600))
        self.centralwidget = QtWidgets.QWidget(Obese)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, -10, 381, 51))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 30, 591, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 70, 771, 151))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 240, 771, 51))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 310, 761, 61))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(20, 380, 741, 121))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(20, 510, 451, 21))
        self.label_7.setObjectName("label_7")
        self.HomeButton = QtWidgets.QPushButton(self.centralwidget)
        self.HomeButton.setGeometry(QtCore.QRect(690, 540, 93, 28))
        self.HomeButton.setObjectName("HomeButton")
        self.BackButton = QtWidgets.QPushButton(self.centralwidget)
        self.BackButton.setGeometry(QtCore.QRect(4, 540, 93, 28))
        self.BackButton.setObjectName("BackButton")
        Obese.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Obese)
        self.statusbar.setObjectName("statusbar")
        Obese.setStatusBar(self.statusbar)

        self.retranslateUi(Obese)
        QtCore.QMetaObject.connectSlotsByName(Obese)

    def retranslateUi(self, Obese):
        _translate = QtCore.QCoreApplication.translate
        Obese.setWindowTitle(_translate("Obese", "Obese"))
        self.label.setText(_translate("Obese", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">ข้อแนะนำสำหรับ อ้วน (Obese)</span></p></body></html>"))
        self.label_2.setText(_translate("Obese", "<html><head/><body><p><span style=\" font-size:11pt;\">คุณ อ้วนแล้ว โดยทั่วไปค่าดัชนีมวลกายปกติมีมากกว่า 25 </span></p></body></html>"))
        self.label_3.setText(_translate("Obese", "<html><head/><body><p><span style=\" font-size:10pt;\">1. ควรควบคุมอาหารโดยลดปริมาณอาหารหรือปรับเปลี่ยนอาหารจากที่ให้พลังงานมากเป็นอาหารที่ให้พลังงานน้อย </span></p><p><span style=\" font-size:10pt;\">ทั้งนี้พลังงานที่ได้รับไม่ควรต่ำกว่า 1200 กิโลแคลอรีต่อวันโดยลดอาหารไขมัน/เนื้อสัตว์ อาหารผัด/ทอด ขนมหวาน </span></p><p><span style=\" font-size:10pt;\">เครื่องดื่มที่ใส่น้ำตาล แอลกอฮอล์แต่ต้องกินอาหารให้หลากหลายในสัดส่วนที่เหมาะสมกินข้าวและแป้งรวมทั้ง</span></p><p><span style=\" font-size:10pt;\">เมล็ดธัญพืชอื่น ๆ ไม่น้อยกว่าวันละ 6 ทัพพี กินผักรวมทั้งเมล็ดถั่วผลไม้ไม่ต่ำกว่าวันละ 5 ส่วน หรือครึ่งกิโลกรัมเพื่อ</span></p><p><span style=\" font-size:10pt;\">ลดพลังงานเข้าร่างกายจะได้ใช้พลังงานส่วนเกินที่สะสมอยู่ในรูปไขมันแทน</span></p></body></html>"))
        self.label_4.setText(_translate("Obese", "<html><head/><body><p><span style=\" font-size:10pt;\">2. ควรเคลื่อนไหวและออกกำลังกายแบบแอโรบิกอย่างสม่ำเสมอทุกวันหรือเกือบทุกวันอย่างน้อยให้เหนื่อยพอควร</span></p><p><span style=\" font-size:10pt;\">โดยหายใจกระชั้นขึ้น ประมาณ 40-60 นาทีต่อวัน</span></p></body></html>"))
        self.label_5.setText(_translate("Obese", "<html><head/><body><p><span style=\" font-size:10pt;\">3. ควรฝึกความแข็งแรงของกล้ามเนื้อด้วยการฝึกกายบริหารหรือยกน้ำหนักจะช่วยเสริมให้ร่างกายมีการใช้พลังงาน</span></p><p><span style=\" font-size:10pt;\">เพิ่มมากขึ้น ทำให้ไขมันลดลง</span></p></body></html>"))
        self.label_6.setText(_translate("Obese", "<html><head/><body><p><span style=\" font-size:10pt;\">4. ถ้าคุณสามารถลดพลังงานเข้าจากอาหารลงได้วันละ 400 กิโลแคลอรี และเพิ่มการใช้พลังงานจากการ</span></p><p><span style=\" font-size:10pt;\">ออกกำลังกายวันละ 200 กิโลแคลอรี รวมแล้วคุณมีพลังงาพร่องลงไปวันละ 600 กิโลแคลอรี ออกกำลังกาย</span></p><p><span style=\" font-size:10pt;\">ประมาณ 6 วัน คิดเป็นพลังงานพร่อง 3600 กิโลแคลอรี คุณจะลดไขมันลงได้ประมาณครึ่งกิโลกรัมต่อสัปดาห์ </span></p><p><span style=\" font-size:10pt;\">พลังงานเข้าหรือออก 3500 กิโลแคลอรี จะเพิ่มหรือลดไขมันได้ 1 ปอนด์ หรือ 0.45 กิโลกรัม</span></p></body></html>"))
        self.label_7.setText(_translate("Obese", "<html><head/><body><p><span style=\" font-size:10pt;\">5. ควรปรึกษาแพทย์หรือผู้เชี่ยวชาญในการลดและควบคุมน้ำหนัก</span></p></body></html>"))
        self.HomeButton.setText(_translate("Obese", "Home"))
        self.BackButton.setText(_translate("Obese", "Back"))
